/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        caddie: {
          bg: '#F2EEE5',
          surface: '#FBF8F1',
          'surface-2': '#EBE5D6',
          line: '#D9D2BF',
          'line-strong': '#9F9580',
          ink: '#1C211C',
          'ink-dim': '#5C6356',
          'ink-mute': '#8A8B7E',
          accent: '#1F3D2C',
          'accent-ink': '#F2EEE5',
          pos: '#1F3D2C',
          neg: '#A33A2A',
          warn: '#A66A1F',
          chip: '#EBE5D6',
          'chip-on': '#1F3D2C',
        },
        // Legacy palette — being phased out one screen at a time during the
        // caddie design pass. Remove once no `oga-*` classes remain.
        oga: {
          black: '#111111',
          green: '#1F3D2C',
          'green-light': '#EBE5D6',
          'green-mid': '#9FE1CB',
          'green-dark': '#1F3D2C',
          red: '#A33A2A',
          'red-light': '#F2EEE5',
          'red-dark': '#A33A2A',
          amber: '#A66A1F',
          'amber-light': '#F2EEE5',
          'amber-dark': '#A66A1F',
          'bg-page': '#F2EEE5',
          'bg-card': '#FBF8F1',
          'bg-input': '#FBF8F1',
          border: '#D9D2BF',
          'border-dark': '#9F9580',
          'text-primary': '#1C211C',
          'text-muted': '#5C6356',
          'text-hint': '#8A8B7E',
        },
      },
      fontFamily: {
        serif: ['Fraunces', 'GT Sectra', 'Georgia', 'ui-serif', 'serif'],
        sans: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        kicker: ['10px', { lineHeight: '1.2', letterSpacing: '0.14em' }],
        meta: ['13px', { lineHeight: '1.5' }],
        body: ['15px', { lineHeight: '1.6' }],
        lede: ['17px', { lineHeight: '1.55' }],
        h2: ['22px', { lineHeight: '1.25' }],
        h1: ['28px', { lineHeight: '1.2' }],
        display: ['38px', { lineHeight: '1.1', letterSpacing: '-0.025em' }],
        // Legacy size tokens — kept until the design pass replaces every use.
        xs: ['11px', { lineHeight: '1.4' }],
        sm: ['13px', { lineHeight: '1.5' }],
        base: ['15px', { lineHeight: '1.6' }],
        lg: ['18px', { lineHeight: '1.4' }],
        xl: ['22px', { lineHeight: '1.3' }],
        '2xl': ['28px', { lineHeight: '1.2' }],
        '3xl': ['36px', { lineHeight: '1.1' }],
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        card: '4px',
        sheet: '4px',
      },
      letterSpacing: {
        kicker: '0.14em',
        button: '0.02em',
        tight: '-0.015em',
        display: '-0.025em',
      },
    },
  },
  plugins: [],
}
