// Auto-generated by `supabase gen types typescript --local`. Until then this stub
// keeps typecheck passing in CI environments without a running Supabase instance.
// Replace by running `pnpm --filter @oga/supabase gen-types` after applying migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
