/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        caddie: {
          bg: '#F2EEE5',
          surface: '#FBF8F1',
          'surface-2': '#EBE5D6',
          line: '#D9D2BF',
          'line-strong': '#9F9580',
          ink: '#1C211C',
          'ink-dim': '#5C6356',
          'ink-mute': '#8A8B7E',
          accent: '#1F3D2C',
          'accent-ink': '#F2EEE5',
          pos: '#1F3D2C',
          neg: '#A33A2A',
          warn: '#A66A1F',
          chip: '#EBE5D6',
          'chip-on': '#1F3D2C',
        },
        // Legacy palette — phased out as mobile screens are migrated.
        oga: {
          black: '#1C211C',
          green: '#1F3D2C',
          'green-light': '#EBE5D6',
          'green-mid': '#9FE1CB',
          'green-dark': '#1F3D2C',
          red: '#A33A2A',
          'red-light': '#F2EEE5',
          'red-dark': '#A33A2A',
          amber: '#A66A1F',
          'amber-light': '#F2EEE5',
          'amber-dark': '#A66A1F',
          'bg-page': '#F2EEE5',
          'bg-card': '#FBF8F1',
          'bg-input': '#FBF8F1',
          border: '#D9D2BF',
          'border-dark': '#9F9580',
          'text-primary': '#1C211C',
          'text-muted': '#5C6356',
          'text-hint': '#8A8B7E',
        },
      },
    },
  },
  plugins: [],
}
